CREATE TABLE train_basic_info (
id BIGINT(32)  NOT NULL PRIMARY KEY AUTO_INCREMENT,
train_no VARCHAR(20) NOT NULL COMMENT '车次',
start_station_name VARCHAR(20) NOT NULL COMMENT '始发站',
end_station_name VARCHAR(20) NOT NULL COMMENT '终点站',
depart_station_name VARCHAR(20) NOT NULL COMMENT '出发站',
dest_station_name VARCHAR(20) NOT NULL COMMENT '目的站',
departure_date date not null COMMENT '出发日期',
distance INT(10) NOT NULL COMMENT '距离',
ydz VARCHAR(10) NOT NULL COMMENT '一等座价格',
edz VARCHAR(10) NOT NULL COMMENT '二等座价格',
swz VARCHAR(10) NOT NULL COMMENT '商务座价格',
tdz VARCHAR(10) NOT NULL COMMENT '特等座价格',
rz VARCHAR(10) NOT NULL COMMENT '软座价格',
yz VARCHAR(10) NOT NULL COMMENT '硬座价格',
gjrws VARCHAR(10) NOT NULL COMMENT '高级软卧上铺价格',
gjrwx VARCHAR(10) NOT NULL COMMENT '高级软卧下铺价格',
dws VARCHAR(10) NOT NULL COMMENT '动卧上铺价格',
dwx VARCHAR(10) NOT NULL COMMENT '动卧下铺价格',
ydws VARCHAR(10) NOT NULL COMMENT '一等卧上铺价格',
ydwx VARCHAR(10) NOT NULL COMMENT '一等卧下铺价格',
edws VARCHAR(10) NOT NULL COMMENT '二等卧上铺价格',
edwz VARCHAR(10) NOT NULL COMMENT '二等卧中铺价格',
edwx VARCHAR(10) NOT NULL COMMENT '二等卧下铺价格',
wz VARCHAR(10) NOT NULL COMMENT '无座价格',
qt VARCHAR(10) NOT NULL COMMENT '其它价格',
rws VARCHAR(10) NOT NULL COMMENT '软卧上铺价格',
rwx VARCHAR(10) NOT NULL COMMENT '软卧下铺价格',
yws VARCHAR(10) NOT NULL COMMENT '硬卧上铺价格',
ywz VARCHAR(10) NOT NULL COMMENT '硬卧中铺价格',
ywx VARCHAR(10) NOT NULL COMMENT '硬卧下铺价格',
add_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
INDEX idx_train_no_depart_station_name_dest_station_name_date (train_no,depart_station_name,dest_station_name,departure_date)
);